version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - ./:/app:cached
    tty: true
    ports:
      - "${LOCAL_IP:-127.0.0.1}:8888:8888"
